### ISSUE TITLE
List frameworks and libraries to be used in readme 

### ISSUE THREAD

**Issue by the-ethan-hunt** [NJACKWinterOfCode/nervy-notebooks#1]
A list of frameworks and libraries used like `TensorFlow` or `Torch` can be mentioned in the `ReadMe.md`

**Comment by vanshsoni** [comment]
I want to add list of library used in readme

**Comment by the-ethan-hunt** [comment]
Weren't you working on Issue #5 ? Plus, this one is for newbies who have just entered open-source development  :sweat_smile:

**Comment by vanshsoni** [comment]
This is my first open source development 
As I know about deep learning I asked about that I am working on developing RNN and CNN both.
I have added libraries to the readme file.
If you allow then I will add PR.

**Comment by the-ethan-hunt** [comment]
Okay,then. No problem. I am assigning this issue to you

**Comment by vanshsoni** [comment]
I request for PR please check it
