### ISSUE TITLE
List frameworks and libraries in readme

### ISSUE THREAD

**Issue by dhruvapte26** [NJACKWinterOfCode/nervy-notebooks#3]
An indexed list of libraries with corresponding notebooks can be written in `readme.md`

**Comment by MVenkata-Rathnam** [comment]
Can I work on this issue?

**Comment by dhruvapte26** [comment]
Sure! assigned to @MVenkata-Rathnam

**Comment by MVenkata-Rathnam** [comment]
I have added the libraries required for each notebook in the readme.  Please suggest me changes If I have made any mistakes.  In the first pull request, the notebook checkpoints were mistakenly added.  That's the reason I closed that pull request.
