### ISSUE TITLE
Add LSTM-sentiment analysis

### ISSUE THREAD

**Issue by the-ethan-hunt** [NJACKWinterOfCode/nervy-notebooks#4]
Write an `IPython notebook` for LSTM sentiment analysis

**Comment by vanshsoni** [comment]
Hey @the-ethan-hunt I have created LSTM sentiment analysis using tensorflow by referring some documents and datasets.
Can I make PR
Please guide me to do PR for the same 
Thank you for your help

**Comment by the-ethan-hunt** [comment]
Yes, you can :smile: . Please name your file as `LSTM_using_tensorflow.ipynb`. You can then pull request

**Comment by vanshsoni** [comment]
This will be open or will be closed
