### ISSUE TITLE
Add autoencoders

### ISSUE THREAD

**Issue by the-ethan-hunt** [NJACKWinterOfCode/nervy-notebooks#9]
Look up [here](https://en.wikipedia.org/wiki/Autoencoder) and [here](https://github.com/BinRoot/TensorFlow-Book) for more information.

**Comment by vanshsoni** [comment]
@the-ethan-hunt Can I use MNIST data to train and test autoencoders?

**Comment by the-ethan-hunt** [comment]
Yes, you can

**Comment by the-ethan-hunt** [comment]
closing this issue
